export const coinData = [
    { symbol: "BTC", price_usd: 117382.32 },
    { symbol: "ETH", price_usd: 3702.02 },
    { symbol: "USDT", price_usd: 1.0 },
    { symbol: "XRP", price_usd: 3.46 },
    { symbol: "BNB", price_usd: 755.84 },
    { symbol: "SOL", price_usd: 196.12 },
    { symbol: "USDC", price_usd: 1.0 },
    { symbol: "DOGE", price_usd: 0.26 },
    { symbol: "ADA", price_usd: 0.86 },
    { symbol: "TRX", price_usd: 0.31 },
    { symbol: "XLM", price_usd: 0.43 },
    { symbol: "SUI", price_usd: 3.79 },
    { symbol: "LINK", price_usd: 18.38 },
    { symbol: "HBAR", price_usd: 0.2493 },
    { symbol: "BCH", price_usd: 518.1 },
    { symbol: "AVAX", price_usd: 24.09 },
    { symbol: "LEO", price_usd: 8.97 },
    { symbol: "LTC", price_usd: 113.82 },
    { symbol: "HYPE", price_usd: 44.14 },
    { symbol: "WBT", price_usd: 44.15 },
];
